%YAML:1.0

use_imu: 1
estimate_extrinsic: 1

cam0_topic: "/cam0/image_raw"
cam1_topic: "/cam1/image_raw"
imu0_topic: "/imu0"
ground_truth_topic: "/leica/position"

output_path: "data/"

cam0_calib: "cam0_mei.yaml"
cam1_calib: "cam1_mei.yaml"

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
F_threshold: 1.0        # ransac threshold (pixel)

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
           0.999557249008, 0.0149672133247, 0.025715529948,  -0.064676986768,
           -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
           0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0125552670891, -0.999755099723, 0.0182237714554, -0.0198435579556,
           0.999598781151, 0.0130119051815, 0.0251588363115, 0.0453689425024,
          -0.0253898008918, 0.0179005838253, 0.999517347078, 0.00786212447038,
          0, 0, 0, 1]

window_size: 10

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
gravity: 9.81007     # gravity magnitude

focal_length: 460.0
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
minimizer_progress_to_stdout: 1


#################################################################################
# loop closing config

image_width: 752
image_height: 480

debug_image: 1
